apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([^"]+)"'
          url: 'http://localhost:16686/trace/{{ value }}'
        - name: correlation_id
          matcherRegex: '"correlationId":"([^"]+)"'
          url: 'http://localhost:3001/explore?left={"range":{"from":"now-1h","to":"now"},"expr":"{correlationId=\"{{ value }}\"}"}'